name: Daily Update

on:
  schedule:
    # 每天 UTC 16:00 运行（北京时间 0:00）
    - cron: '0 16 * * *'
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x

      - name: Init workspace
        run: deno task init

      - name: Run Genshin Impact Birthday task
        run: deno task gi-birthday
        continue-on-error: true

      - name: Run Genshin Impact Event task
        run: deno task gi-event
        continue-on-error: true

      - name: Run Star Rail Event task
        run: deno task sr-event
        continue-on-error: true

      - name: Run ZZZ Birthday task
        run: deno task zzz-birthday
        continue-on-error: true

      - name: Run ZZZ Event task
        run: deno task zzz-event
        continue-on-error: true

      - name: Run Arknights Birthday task
        run: deno task ark-birthday
        continue-on-error: true

      - name: Run Arknights Event task
        run: deno task ark-event
        continue-on-error: true

      - name: Run Blue Archive Birthday task
        run: deno task ba-birthday
        continue-on-error: true

      - name: Run Blue Archive Event task
        run: deno task ba-event
        continue-on-error: true

      - name: Run Wuthering Waves Event task
        run: deno task ww-event
        continue-on-error: true

      - name: Commit and push if changes exist
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -A

          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "chore: daily update $(date +%Y-%m-%d)"
          git push